parameter_defaults:
  fe_name: playlister2_fe
  be_name: playlister2_be
  fe_key_name: cliff_admin
  be_key_name: cliff_admin
  fe_image: "centos-feralcoder-8.3"
  be_image: "centos-feralcoder-8.3"
  fe_instance_type: "m1.medium"
  be_instance_type: "m1.medium"
  fe_ports: "80,443,8080,22"
  be_ports: "22,7000,7001,7199,9042,9142,9160"
  fe_subnets: "admin1-subnet"
  fe_networks: "admin1-net"
  be_subnets: "admin1-subnet"
  be_networks: "admin1-net"

  # VARS FOR playlister.yaml
  fe_vip: "172.30.1.12"
  private_network: admin1-net
  public_network: public1
  vip_subnet: public1-subnet


#resource_registry:  
#    "OS::Nova::Server::PLFrontend": "frontend.yaml"
#    "OS::Nova::Server::PLBackend": "backend.yaml"

