parameter_defaults:
  fe_name: playlister2_fe
  olap_name: playlister2_olap
  oltp_name: playlister2_oltp
  fe_key_name: cliff_admin
  olap_key_name: cliff_admin
  oltp_key_name: cliff_admin
  fe_image: "centos-feralcoder-8.3"
  olap_image: "centos-feralcoder-8.3"
  oltp_image: "centos-feralcoder-8.3"
  fe_instance_type: "m1.medium"
  olap_instance_type: "m1.medium"
  oltp_instance_type: "m1.medium"
  fe_subnets: "admin1-subnet"
  fe_networks: "admin1-net"
  olap_subnets: "admin1-subnet"
  olap_networks: "admin1-net"
  oltp_subnets: "admin1-subnet"
  oltp_networks: "admin1-net"

  # VARS FOR playlister.yaml
  fe_vip: "172.30.1.12"
  olap_vip: "172.30.1.22"
  oltp_vip: "172.30.1.32"
  private_network: admin1-net
  public_network: public1
  vip_subnet: public1-subnet


#resource_registry:  
#    "OS::Nova::Server::PLFrontend": "frontend.yaml"
#    "OS::Nova::Server::PLBackend": "backend.yaml"

