parameter_defaults:
  fe_name: playlister_fe
  be_name: playlister_be
  fe_key_name: cliff_admin
  be_key_name: cliff_admin
  fe_image_id: "ubuntu-20.4"
  be_image_id: "ubuntu-20.4"
  fe_instance_type: "m1.medium"
  be_instance_type: "m1.medium"
  fe_ports: "80,443,8080,22"
  be_ports: "22,7000,7001,7199,9042,9142,9160"
  fe_subnets: "admin1-subnet"
  fe_networks: "admin1-net"
  be_subnets: "admin1-subnet"
  be_networks: "admin1-net"

#resource_registry:  
#    "OS::Nova::Server::PLFrontend": "frontend.yaml"
#    "OS::Nova::Server::PLBackend": "backend.yaml"

